language: python
python:
  - 2.7
  - 3.6
os: 
  - linux
  - osx
  - windows
script:
   - python setup.py build_ext --inplace
   - export PYTHONPATH=/home/travis/build/fastlmm/PySnpTools
   - python tests/test.py
notifications:
  email:
    recipients:
      - carlk@msn.com
    on_success: always
    on_failure: always
