language: python
python: 2.7
python: 3.6
matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode11.2
      language: shell
      before_install:
        - python3 -m pip install --upgrade pip setuptools
    - os: windows
      language: shell
notifications:
  email:
    recipients:
      - carlk@msn.com
    on_success: always
    on_failure: always
