language: python
script:
   - python setup build_ext --inplace
   - export PYTHONPATH=.
   - python tests/test.py
notifications:
  email:
    recipients:
      - carlk@msn.com
    on_success: always
    on_failure: always
