language: python
python: 3.7
matrix:
  include:
    - os : linux
      before_install:
        - pip install -r requirements.txt
    - os: osx
      osx_image: xcode11.2
      language: shell
      before_install:
        - pip install -r requirements.txt
    - os : windows
      language: shell
      before_install:
        - choco install python --version 3.8.1 --no-progress
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        - cp /c/Python38/python.exe /c/Python38/python3.exe
        - pip install -r requirements.txt

install:
   - python setup.py build_ext --inplace
script:
   - export PYTHONPATH={project}
   - python tests/test.py
notifications:
  email:
    recipients:
      - carlk@msn.com
    on_success: always
    on_failure: always
