language: python
matrix:
  include:
  - name: linux 3
    python: 3.6
    os: linux
    before_install:
    - pip install -r requirements.txt

  - name: linux 2
    python: 2.7
    os: linux
    before_install:
    - pip install -r requirements.txt

  - os: osx
    osx_image: xcode11.2
    language: shell
    before_install:
    - pip install -r requirements.txt

  - name: Windows 3
    os: windows
    language: shell
    before_install:
    - choco install python --version 3.8.1 --no-progress
    - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
    - cp /c/Python38/python.exe /c/Python38/python3.exe
    - pip install -r requirements.txt
    - pip install wheel

  - name: Windows 2
    os: windows
    language: shell
    before_install:
    - choco install python2 --no-progress
    - choco install --ignore-dependencies vcpython27
    - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
    - pip install -r requirements.txt
    - pip install wheel

install:
- python setup.py build_ext --inplace
- python setup.py sdist bdist_wheel

script:
- export PYTHONPATH=$TRAVIS_BUILD_DIR
- python tests/test.py

deploy:
  provider: releases
  api_key:
    secure: "QBOCfV4l8WPHZoOIf/C86V2vBl7mkpHzsdC/NeScCk9TXB3YZmzFgVYGWSboa0vEwMuAm/sgCYswc5Kt+gLxYE7Zd2XT0I1MbKjMyejB1EsCIkcSytaCPJft3lZnCksXOityuPltmZ535LJHkBVsAG5BRC1p8R0h6tRRROWRcuIKU+k0NbQ5awLjaUQMq/OkBWi/8aMl9MS72xJ7iYVvsUYGgeShZtM/lMxCMpEt841rT704T/OvpIUuDzJsrmDIaKl179ODNogLjTANbP19m5g5iJgBHwOrelV6nfvCrd2/abp6K0tv+qFPGpNMHsChwZYjZY1zdtE6BQk59yTebJ/X8Z0uLB3sR/N8pmbURD7koP6oqld3iTU6dkPCrAf6dYAVNVaJmrFPTfelizTpoA/2j0aZdfzAih7q8mGihgKuH7o7yKO9TmTQuXbB0zRZFamEH71BC9xuYiXL8XGeyeUgedD2NJ0eb24rAPuPEy0nfESc13x3snsUVz6tneV6Z5sc7MA+KeqgFmhOrxgcRHO1MQtB35slMgQSc18b0tthjfRW8sIvszMV6yAdNdx0WfoX1YwfSKgDXAgwMUZpPTuKPFb38TM7Q0bgGk7YO0w0TPGflo2mvgOuXeECsE2qSReRuECpqW55YVgyL1rzD+x/FoO/nYuM4msNQFZRiO0="
  file_glob: true
  file: dist/*
  overwrite: true
  skip_cleanup: true
  draft: true
  prerelease: true
  on:
    repo: fastlmm/PySnpTools
    all_branches: true

#deploy:
#  provider: releases
#  api_key:
#    secure: 
#  file: dist/*
#  overwrite: true
#  skip_cleanup: true
#  draft: true
#  prerelease: true
#  on:
#    repo: fastlmm/PySnpTools
#    all_branches: true


#deploy:
#  provider: script
# #script: bash -c "ls -las dist"
#  script: bash -c "echo $NOT_NEEDED"
#  skip_cleanup: true
#  on:
#    branch: dev

notifications:
  email:
    recipients:
    - carlk@msn.com
    on_success: always
    on_failure: always
