language: python
python:
  - 2.7
  - 3.6
matrix:
  include:
    #- os : linux
    - os: osx
      osx_image: xcode11.2
    - os : windows
      before_install:
        - choco install python --version 3.8.1 --no-progress
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        - cp /c/Python38/python.exe /c/Python38/python3.exe

script:
   - python setup.py build_ext --inplace
   - export PYTHONPATH=/home/travis/build/fastlmm/PySnpTools
   - python tests/test.py
notifications:
  email:
    recipients:
      - carlk@msn.com
    on_success: always
    on_failure: always
