language: python
python:
    - "2.7"
    - "3.6"
matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode11.2
      language: shell
    - os: windows
      language: shell
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install: pip3 install --upgrade pip
notifications:
  email:
    recipients:
      - carlk@msn.com
    on_success: always
    on_failure: always
